### ISSUE TITLE
Issue trying to install perl6-ANTLR4

### ISSUE THREAD

**Issue by jpeep44** [drforr/perl6-ANTLR4#13]
Hi,

My perl6 version is : 
# perl6 --version 
This is Rakudo version 2017.07 built on MoarVM version 2017.07

Trying to install perl6-ANTLRR4, doing : panda update && panda install ANTLR4, I'm getting the following error

...
Result: PASS
==> Installing JSON::Tiny
JSON::Tiny:ver<*>:auth<>:api<> already installed
  in any  at /root/rakudo-star-2017.07/install/share/perl6/site/precomp/531476C94944C40F030060AEB60539343668769B.1501425692.30551/58/582CB7486602954A4601BDCE5A0EAC54B05DA58A line 1
  in block  at /root/rakudo-star-2017.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 23
  in sub MAIN at /root/rakudo-star-2017.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 20
  in block <unit> at /root/rakudo-star-2017.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 166
  in sub MAIN at /root/rakudo-star-2017.07/install/share/perl6/site/bin/panda line 2
  in block <unit> at /root/rakudo-star-2017.07/install/share/perl6/site/bin/panda line 2

Any idea ? 

Thanks for your help.
Best Regards,
JP

**Comment by ronaldxs** [comment]
```bash
> zef install ANTLR4::Grammar
```

Worked for me.

**Comment by drforr** [comment]
Now using App:MI6 for release, it's now on both ecosystem and CPAN.
